In [6]:
from keras.models import Sequential
from keras.layers import Dense, Activation
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Generate dummy data
import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(2, size=(1000, 1))
print(np.shape(labels))
# Train the model, iterating on the data in batches of 32 samples
model.fit(data, labels, epochs=100, batch_size=32)

(1000, 1)
Epoch 1/100
1000/1000 [==============================] - 1s 526us/step - loss: 0.7044 - acc: 0.5020
Epoch 2/100
1000/1000 [==============================] - 0s 99us/step - loss: 0.6932 - acc: 0.5310
Epoch 3/100
1000/1000 [==============================] - 0s 105us/step - loss: 0.6845 - acc: 0.5470
Epoch 4/100
1000/1000 [==============================] - 0s 102us/step - loss: 0.6796 - acc: 0.5610
Epoch 5/100
1000/1000 [==============================] - 0s 87us/step - loss: 0.6759 - acc: 0.5650
Epoch 6/100
1000/1000 [==============================] - 0s 87us/step - loss: 0.6695 - acc: 0.5950
Epoch 7/100
1000/1000 [==============================] - 0s 89us/step - loss: 0.6679 - acc: 0.6050
Epoch 8/100
1000/1000 [==============================] - 0s 88us/step - loss: 0.6624 - acc: 0.6030
Epoch 9/100
1000/1000 [==============================] - 0s 93us/step - loss: 0.6590 - acc: 0.6100
Epoch 10/100
1000/1000 [==============================] - 0s 95us/step - loss: 0.6569 - acc: 0.6

1000/1000 [==============================] - 0s 83us/step - loss: 0.3647 - acc: 0.8940
Epoch 83/100
1000/1000 [==============================] - 0s 97us/step - loss: 0.3566 - acc: 0.8890
Epoch 84/100
1000/1000 [==============================] - 0s 87us/step - loss: 0.3513 - acc: 0.9040
Epoch 85/100
1000/1000 [==============================] - 0s 77us/step - loss: 0.3502 - acc: 0.9010
Epoch 86/100
1000/1000 [==============================] - 0s 123us/step - loss: 0.3482 - acc: 0.9020
Epoch 87/100
1000/1000 [==============================] - 0s 129us/step - loss: 0.3375 - acc: 0.9150
Epoch 88/100
1000/1000 [==============================] - 0s 89us/step - loss: 0.3368 - acc: 0.9170
Epoch 89/100
1000/1000 [==============================] - 0s 104us/step - loss: 0.3369 - acc: 0.9070
Epoch 90/100
1000/1000 [==============================] - 0s 89us/step - loss: 0.3282 - acc: 0.9220
Epoch 91/100
1000/1000 [==============================] - 0s 93us/step - loss: 0.3274 - acc: 0.9140
Epoch 92/1

In [22]:
import keras
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Generate dummy data
import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(10, size=(1000, 1))
print(np.shape(data))
# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)
print((type(one_hot_labels)))
# Train the model, iterating on the data in batches of 32 samples
model.fit(data, one_hot_labels, epochs=10, batch_size=32)

(1000, 100)
<class 'numpy.ndarray'>
Epoch 1/10
1000/1000 [==============================] - 1s 720us/step - loss: 2.3631 - acc: 0.0960
Epoch 2/10
1000/1000 [==============================] - 0s 86us/step - loss: 2.3169 - acc: 0.1040
Epoch 3/10
1000/1000 [==============================] - 0s 96us/step - loss: 2.3021 - acc: 0.1150
Epoch 4/10
1000/1000 [==============================] - 0s 115us/step - loss: 2.2901 - acc: 0.1280
Epoch 5/10
1000/1000 [==============================] - 0s 94us/step - loss: 2.2818 - acc: 0.1350
Epoch 6/10
1000/1000 [==============================] - 0s 117us/step - loss: 2.2723 - acc: 0.1460
Epoch 7/10
1000/1000 [==============================] - 0s 131us/step - loss: 2.2648 - acc: 0.1520
Epoch 8/10
1000/1000 [==============================] - 0s 131us/step - loss: 2.2572 - acc: 0.1590
Epoch 9/10
1000/1000 [==============================] - 0s 120us/step - loss: 2.2489 - acc: 0.1690
Epoch 10/10
1000/1000 [==============================] - 0s 100us/step - los

In [17]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD

# Generate dummy data
x_train = np.random.random((100, 100, 100, 3))

y_train = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)
x_test = np.random.random((20, 100, 100, 3))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(20, 1)), num_classes=10)

model = Sequential()
# input: 100x100 images with 3 channels -> (100, 100, 3) tensors.
# this applies 32 convolution filters of size 3x3 each.
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(100, 100, 3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(x_train, y_train, batch_size=32, epochs=10)
score = model.evaluate(x_test, y_test, batch_size=32)

[[[0.35509893 0.51233105 0.20144143]
  [0.99962804 0.0066869  0.90981903]
  [0.14554155 0.22336358 0.24035474]
  ...
  [0.07594434 0.21283451 0.50692172]
  [0.40381429 0.07239479 0.29684215]
  [0.32194109 0.05292316 0.99415227]]

 [[0.76032418 0.99709771 0.04443819]
  [0.4283055  0.94451469 0.49182717]
  [0.51312902 0.24392922 0.54612605]
  ...
  [0.88472249 0.90006223 0.49265764]
  [0.35348726 0.15200632 0.23856056]
  [0.41242372 0.34151141 0.47218939]]

 [[0.39458278 0.07517516 0.79896676]
  [0.2579382  0.60257243 0.13405307]
  [0.30052569 0.14470888 0.82045887]
  ...
  [0.43038759 0.22140297 0.45005627]
  [0.93166166 0.2279163  0.20655027]
  [0.58758007 0.91301512 0.22507337]]

 ...

 [[0.37785374 0.78220051 0.02948516]
  [0.18935976 0.14758568 0.64837992]
  [0.72935765 0.90367468 0.41167399]
  ...
  [0.0451845  0.92544133 0.07173167]
  [0.84385089 0.96028814 0.77052424]
  [0.63530287 0.64615603 0.15229267]]

 [[0.14641363 0.36404463 0.50057129]
  [0.51378986 0.27870303 0.01793441]


In [28]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM
x_train = np.random.random((1000,100))
print(x_train)
y_train = np.random.randint(10, size=(1000, 1))
max_features=100
model = Sequential()
model.add(Embedding(max_features, output_dim=256))
model.add(LSTM(128))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=16, epochs=10)
#score = model.evaluate(x_test, y_test, batch_size=16)

[[0.83058547 0.21022561 0.75756909 ... 0.81888062 0.55739231 0.50196089]
 [0.59255148 0.25485721 0.79170688 ... 0.00637492 0.46680298 0.2677139 ]
 [0.49294116 0.23428845 0.3651189  ... 0.96108648 0.35980837 0.24739918]
 ...
 [0.26173503 0.39793571 0.29905779 ... 0.89036362 0.69655774 0.20347083]
 [0.92373776 0.94230026 0.00175105 ... 0.62647792 0.92114621 0.23187652]
 [0.90749982 0.28865667 0.33188777 ... 0.22875544 0.78686939 0.07082126]]
Epoch 1/10
1000/1000 [==============================] - 23s 23ms/step - loss: -48.2343 - acc: 0.0940
Epoch 2/10
1000/1000 [==============================] - 21s 21ms/step - loss: -54.5548 - acc: 0.0940
Epoch 3/10
1000/1000 [==============================] - 22s 22ms/step - loss: -54.6145 - acc: 0.0940
Epoch 4/10
1000/1000 [==============================] - 21s 21ms/step - loss: -54.6186 - acc: 0.0940
Epoch 5/10
1000/1000 [==============================] - 21s 21ms/step - loss: -54.6117 - acc: 0.0940
Epoch 6/10
1000/1000 [=============================

ValueError: Error when checking input: expected embedding_5_input to have 2 dimensions, but got array with shape (20, 100, 100, 3)

In [29]:

input_array = np.random.randint(1000, size=(32, 10))

In [31]:
np.shape(input_array)

(32, 10)

In [32]:
model = Sequential()
model.add(Embedding(1000, 64, input_length=10))
# the model will take as input an integer matrix of size (batch, input_length).
# the largest integer (i.e. word index) in the input should be no larger than 999 (vocabulary size).
# now model.output_shape == (None, 10, 64), where None is the batch dimension.

input_array = np.random.randint(1000, size=(32, 10))

model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
assert output_array.shape == (32, 10, 64)

In [33]:
print(output_array)

[[[-0.04500184 -0.01970725 -0.00953742 ... -0.02298778 -0.02077987
   -0.01409354]
  [-0.04436594 -0.02491027  0.00550988 ...  0.02500151  0.02646646
   -0.0233621 ]
  [-0.04746424 -0.01483731  0.02343686 ... -0.00502846 -0.00478787
   -0.02038908]
  ...
  [-0.00446964  0.02333269  0.04115755 ...  0.00967966 -0.00925871
    0.02962151]
  [ 0.00578    -0.01918393 -0.02849885 ... -0.01344421  0.01880512
    0.04046163]
  [-0.03221711  0.02678839  0.03209445 ...  0.04094783  0.04918135
    0.04926416]]

 [[-0.02956951  0.00153489 -0.04250584 ...  0.03026488 -0.03427526
   -0.04028121]
  [-0.02249992  0.00022874 -0.02191315 ...  0.02925037 -0.04634261
    0.0281576 ]
  [-0.015022    0.04217513 -0.00298848 ...  0.03961286  0.04850599
   -0.01174487]
  ...
  [ 0.0391278  -0.02705768 -0.02704747 ...  0.00821186 -0.02644001
   -0.01688623]
  [ 0.03272783 -0.01134402  0.01990436 ...  0.04052139 -0.03238566
   -0.02276134]
  [-0.01256595 -0.01742699  0.02462817 ... -0.01976378 -0.02871933
    0.